jobs:
  build:
    if: ${{ github.repository == 'Netflix/spectator' }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Gradle wrapper validation
      uses: gradle/wrapper-validation-action@v1
    - continue-on-error: true
      name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: zulu
        java-version: 21
    - continue-on-error: true
      run: echo "JDK21=$JAVA_HOME" >> $GITHUB_ENV
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: zulu
        java-version: 17
    - continue-on-error: true
      run: echo "JDK17=$JAVA_HOME" >> $GITHUB_ENV
    - continue-on-error: true
      name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      run: echo "JDK8=$JAVA_HOME" >> $GITHUB_ENV
    - continue-on-error: true
      env:
        NETFLIX_OSS_REPO_PASSWORD: ${{ secrets.ORG_NETFLIXOSS_PASSWORD }}
        NETFLIX_OSS_REPO_USERNAME: ${{ secrets.ORG_NETFLIXOSS_USERNAME }}
        NETFLIX_OSS_SIGNING_KEY: ${{ secrets.ORG_SIGNING_KEY }}
        NETFLIX_OSS_SIGNING_PASSWORD: ${{ secrets.ORG_SIGNING_PASSWORD }}
      if: contains(github.ref, '-rc.')
      name: Build candidate
      run: ./gradlew --info --stacktrace -Prelease.useLastTag=true candidate
    - continue-on-error: true
      env:
        NETFLIX_OSS_REPO_PASSWORD: ${{ secrets.ORG_NETFLIXOSS_PASSWORD }}
        NETFLIX_OSS_REPO_USERNAME: ${{ secrets.ORG_NETFLIXOSS_USERNAME }}
        NETFLIX_OSS_SIGNING_KEY: ${{ secrets.ORG_SIGNING_KEY }}
        NETFLIX_OSS_SIGNING_PASSWORD: ${{ secrets.ORG_SIGNING_PASSWORD }}
        NETFLIX_OSS_SONATYPE_PASSWORD: ${{ secrets.ORG_SONATYPE_PASSWORD }}
        NETFLIX_OSS_SONATYPE_USERNAME: ${{ secrets.ORG_SONATYPE_USERNAME }}
      if: (!contains(github.ref, '-rc.'))
      name: Build release
      run: ./gradlew --info -Prelease.useLastTag=true final
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
